# Generated by Django 4.0.4 on 2022-06-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_alter_operation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_operation', to='dataapp.post'),
        ),
    ]
