# Generated by Django 4.0.4 on 2022-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_alter_operation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='high_proportion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='low_proportion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='middle_proportion',
            field=models.IntegerField(null=True),
        ),
    ]
