# Generated by Django 4.0.4 on 2022-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0008_operation_high_proportion_operation_low_proportion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='high_proportion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='low_proportion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='middle_proportion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
